import { StyleSheet } from 'react-native';
import { colors } from '@/theme/colors';

export const taskDetailStyles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: colors.background,
  },
  loadingText: { 
    color: colors.textMuted, 
    marginTop: 10,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 8,
    marginBottom: 4,
    backgroundColor: colors.surface,
    height: 40,
    zIndex: 1000,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    marginRight: 15,
  },
  backButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3b82f6',
    marginLeft: 8,
  },
  taskInfoBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: colors.surfaceElevated,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  taskInfoType: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textMuted,
  },
  taskInfoPriceBadge: {
    backgroundColor: colors.accentPurple,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  taskInfoPriceText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '600',
  },
  annotationLayout: {
    flex: 1,
    flexDirection: 'row',
  },
  leftToolbarCol: {
    width: 60,
    minWidth: 60,
    maxWidth: 60,
    padding: 4,
    backgroundColor: colors.surface,
    borderRightWidth: 1,
    borderRightColor: colors.border,
    flexDirection: 'column',
    gap: 4,
  },
  toolBtnLarge: {
    width: 48,
    height: 48,
    borderRadius: 6,
    backgroundColor: '#374151',
    borderWidth: 1,
    borderColor: '#4b5563',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 2,
    marginBottom: 6,
  },
  toolBtnActivePurple: {
    backgroundColor: colors.accentPurple,
    borderColor: colors.accentPurple,
  },
  toolBtnLargeText: { 
    fontSize: 9, 
    color: colors.text, 
    textAlign: 'center', 
    marginTop: 2, 
    fontWeight: '600', 
    textTransform: 'uppercase', 
    letterSpacing: 0.5, 
  },
  annotationMain: {
    flex: 1,
    backgroundColor: colors.background,
  },
  annotationCanvasWrapFullWidth: {
    flex: 1,
  },
  canvasWorkspace: {
    flex: 1,
    position: 'relative',
    backgroundColor: colors.background,
  },
  canvasGridOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: 'none',
  },
  rightSidebar: {
    width: 280,
    backgroundColor: colors.surfaceElevated,
    borderLeftWidth: 1,
    borderLeftColor: colors.border,
    padding: 16,
  },
  rightSidebarTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 16,
  },
  objectList: {
    flex: 1,
  },
  objectListEmpty: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  objectCardWrap: {
    marginBottom: 12,
  },
  objectCard: {
    backgroundColor: colors.surface,
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  objectCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  objectCardTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  footer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  submitContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  submitButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
  },
  submitExitButton: {
    backgroundColor: colors.info,
  },
  submitSaveButton: {
    backgroundColor: colors.success,
  },
  submitButtonText: { 
    fontSize: 14, 
    fontWeight: '600', 
    color: colors.text, 
  },
  submittedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: colors.success,
  },
  submittedText: { 
    fontSize: 14, 
    fontWeight: '600', 
    color: colors.text, 
  },
  aiButtonWrapper: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  aiTranscribeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.accentPurple,
    borderRadius: 8,
  },
  aiTranscribeButtonDisabled: { 
    opacity: 0.6 
  },
  aiTranscribeButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  transcriptionCard: {
    margin: 16,
    backgroundColor: colors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  transcriptionInput: {
    minHeight: 120,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    color: colors.text,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  audioSection: {
    backgroundColor: colors.surfaceElevated,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  audioHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  sectionLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  audioPlayerWrapper: {
    padding: 16,
  },
  noAudioText: {
    fontSize: 14,
    color: colors.textMuted,
    fontStyle: 'italic',
    textAlign: 'center',
    padding: 20,
  },
  transcriptionSection: {
    backgroundColor: colors.surfaceElevated,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  transcriptionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
});

export default taskDetailStyles;
