import { StyleSheet } from 'react-native';
import type { ProThemeColors } from '@/theme/videoProWorkbenchTheme';

/** LiDAR workbench: colors + layout (pairs with createVideoProWorkbenchStyles for shell). */
export function createLidarAnnotationLayoutStyles(c: ProThemeColors) {
  return StyleSheet.create({
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 12, backgroundColor: c.bg },
    muted: { color: c.textMuted, fontSize: 13 },
    viewport: { flex: 1, minWidth: 0, minHeight: 0, backgroundColor: c.bg },
    sideScroll: { flex: 1, minHeight: 0, paddingHorizontal: 10, paddingTop: 10, paddingBottom: 16 },
    sideTitle: { color: c.text, fontWeight: '700', fontSize: 14, marginBottom: 4 },
    sideHint: { color: c.textSoft, fontSize: 11, marginBottom: 10 },
    railToolTall: {
      position: 'relative' as const,
      alignSelf: 'stretch',
      minHeight: 56,
      borderRadius: c.radius,
      backgroundColor: c.panel,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 4,
      paddingHorizontal: 4,
      gap: 2,
    },
    railToolTallOn: {
      borderColor: c.accent,
      backgroundColor: c.accentMuted,
    },
    railToolTxt: {
      color: c.textMuted,
      fontWeight: '600',
      fontSize: 9,
      textAlign: 'center',
    },
    railToolTxtOn: { color: c.accent },
    railDivider: {
      height: 1,
      backgroundColor: c.border,
      marginVertical: 8,
      alignSelf: 'stretch',
    },
    railSectionLabel: {
      color: c.textSoft,
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 4,
      alignSelf: 'stretch',
    },
    railChip: {
      alignSelf: 'stretch',
      paddingVertical: 6,
      paddingHorizontal: 4,
      borderRadius: c.radius,
      backgroundColor: c.panel,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: 'center',
    },
    railChipOn: {
      borderColor: c.accent,
      backgroundColor: c.accentMuted,
    },
    railChipTxt: {
      color: c.textMuted,
      fontSize: 10,
      fontWeight: '600',
      textAlign: 'center',
    },
    railChipTxtOn: { color: c.accent },
    railClassPill: {
      alignSelf: 'stretch',
      paddingVertical: 12,
      paddingHorizontal: 10,
      borderRadius: 999,
      backgroundColor: c.panel,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: 'center',
      marginBottom: 8,
    },
    railClassPillOn: {
      borderColor: c.accent,
      backgroundColor: c.accentMuted,
    },
    railClassPillTxt: {
      color: c.textMuted,
      fontSize: 13,
      fontWeight: '700',
      textAlign: 'center',
    },
    railClassPillTxtOn: { color: c.accent },
    railSectionTitle: {
      color: c.textSoft,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1.2,
      marginBottom: 8,
      marginTop: 4,
      alignSelf: 'stretch',
    },
    rowItem: {
      padding: 10,
      borderRadius: c.radius,
      backgroundColor: c.panel,
      marginBottom: 6,
      borderWidth: 1,
      borderColor: c.border,
    },
    rowItemOn: { borderColor: c.accent, backgroundColor: c.accentMuted },
    rowItemTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 6,
    },
    rowItemClassTag: {
      color: c.textMuted,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
    },
    rowSelectLink: { color: c.accent, fontSize: 11, fontWeight: '600' },
    rowNameInput: {
      backgroundColor: c.bg,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: c.radius,
      paddingVertical: 8,
      paddingHorizontal: 10,
      color: c.text,
      fontSize: 13,
    },
    form: { marginTop: 16, paddingTop: 12, borderTopWidth: 1, borderTopColor: c.border },
    formTitle: { color: c.text, fontWeight: '700', marginBottom: 10 },
    field: { marginBottom: 10 },
    fieldL: { color: c.textMuted, fontSize: 11, marginBottom: 4 },
    inp: {
      backgroundColor: c.bg,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: c.radius,
      padding: 10,
      color: c.text,
      fontSize: 14,
    },
    delBtn: { marginTop: 12, padding: 10, borderRadius: c.radius, backgroundColor: 'rgba(239,83,80,0.12)' },
    delTxt: { color: c.danger, textAlign: 'center', fontWeight: '600' },
    submitted: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      padding: 16,
      borderTopWidth: 1,
      borderTopColor: c.border,
      backgroundColor: c.panel,
    },
    submittedTxt: { color: c.accent, fontWeight: '700' },

    /** LiDAR left rail (2×48 + gap = 100px inner, matches video rail proportions). */
    lidarRailCol: { width: 100, alignSelf: 'center', gap: 4, paddingBottom: 8 },
    lidarToolRow: {
      width: 100,
      alignSelf: 'center',
      flexDirection: 'row',
      gap: 4,
      justifyContent: 'flex-start',
    },
    lidarTool48: {
      width: 48,
      maxWidth: 48,
      minHeight: 54,
      borderRadius: c.radius,
      backgroundColor: c.panel,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 2,
      paddingHorizontal: 2,
      gap: 2,
      position: 'relative' as const,
    },
    lidarTool48On: {
      borderColor: c.accent,
      backgroundColor: c.accentMuted,
    },
    lidarTool48Txt: {
      color: c.textMuted,
      fontWeight: '600',
      fontSize: 8,
      textAlign: 'center',
    },
    lidarTool48TxtOn: { color: c.accent },
    lidarToolSpacer: { width: 48, minHeight: 54 },
    lidarToolFull: {
      width: 100,
      alignSelf: 'center',
      minHeight: 54,
      borderRadius: c.radius,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.panel,
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 6,
      gap: 2,
      position: 'relative' as const,
    },
    lidarUndoFull: {
      borderColor: 'rgba(59, 130, 246, 0.55)',
      backgroundColor: 'rgba(59, 130, 246, 0.1)',
    },
    lidarCenterFull: {
      borderColor: 'rgba(16, 185, 129, 0.5)',
      backgroundColor: 'rgba(16, 185, 129, 0.1)',
    },
    lidarToolFullTxt: { fontSize: 11, fontWeight: '700', color: c.text, textAlign: 'center' },
    lidarKeyCap: {
      position: 'absolute' as const,
      bottom: 4,
      right: 6,
      fontSize: 8,
      fontWeight: '700',
      color: c.textSoft,
    },
    lidarRailHint: {
      fontSize: 9,
      color: c.textSoft,
      textAlign: 'center',
      marginTop: 6,
      paddingHorizontal: 2,
      lineHeight: 12,
    },

    objectCardWrap: { marginBottom: 8 },
    objectCard: {
      backgroundColor: c.panel,
      borderRadius: 12,
      padding: 12,
      borderWidth: 1,
      borderColor: c.border,
    },
    objectCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    objectCardTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: c.text,
      flex: 1,
      marginRight: 8,
    },
    lidarLabelChipGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    lidarLabelChip: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 14,
      backgroundColor: 'transparent',
      borderWidth: 1,
      maxWidth: '100%',
    },
    lidarLabelChipTxt: { fontSize: 10, fontWeight: '600', flexShrink: 1 },
  });
}
