import { StyleSheet } from 'react-native';
import type { AppColors } from '@/theme/palettes';

/** Tab task detail / video annotation layout — kept outside `app/` so Expo Router does not treat it as a route. */
export function createTabTaskDetailStyles(themeColors: AppColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: themeColors.background,
    },
    loadingText: {
      color: themeColors.textMuted,
      marginTop: 10,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 8,
      marginBottom: 4,
      backgroundColor: themeColors.surface,
      height: 40,
      zIndex: 1000,
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 8,
      backgroundColor: 'rgba(59, 130, 246, 0.1)',
      marginRight: 15,
    },
    backButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: themeColors.accent,
      marginLeft: 8,
    },
    taskInfoBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 12,
      backgroundColor: themeColors.surfaceElevated,
      borderBottomWidth: 1,
      borderBottomColor: themeColors.border,
    },
    taskInfoType: {
      fontSize: 14,
      fontWeight: '600',
      color: themeColors.textMuted,
    },
    taskInfoPriceBadge: {
      backgroundColor: themeColors.accentPurple,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 12,
    },
    taskInfoPriceText: {
      color: themeColors.onAccent,
      fontSize: 12,
      fontWeight: '600',
    },
    annotationLayout: {
      flex: 1,
      flexDirection: 'row',
    },
    leftToolbarCol: {
      width: 60,
      minWidth: 60,
      maxWidth: 60,
      padding: 4,
      backgroundColor: themeColors.surface,
      borderRightWidth: 1,
      borderRightColor: themeColors.border,
      flexDirection: 'column',
      gap: 4,
    },
    toolBtnLarge: {
      width: 48,
      height: 48,
      borderRadius: 6,
      backgroundColor: themeColors.surfaceElevated,
      borderWidth: 1,
      borderColor: themeColors.border,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'column',
      gap: 2,
      marginBottom: 6,
    },
    toolBtnActivePurple: {
      backgroundColor: themeColors.accentPurple,
      borderColor: themeColors.accentPurple,
    },
    toolBtnLargeText: {
      fontSize: 9,
      color: themeColors.text,
      textAlign: 'center',
      marginTop: 2,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    annotationMain: {
      flex: 1,
      backgroundColor: themeColors.background,
    },
    annotationCanvasWrapFullWidth: {
      flex: 1,
    },
    canvasWorkspace: {
      flex: 1,
      position: 'relative',
      backgroundColor: themeColors.background,
    },
    canvasGridOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      pointerEvents: 'none',
    },
    rightSidebar: {
      width: 280,
      backgroundColor: themeColors.surfaceElevated,
      borderLeftWidth: 1,
      borderLeftColor: themeColors.border,
      padding: 16,
    },
    rightSidebarTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: themeColors.text,
      marginBottom: 16,
    },
    objectList: {
      flex: 1,
    },
    objectListEmpty: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    objectCardWrap: {
      marginBottom: 12,
    },
    objectCard: {
      backgroundColor: themeColors.surface,
      borderRadius: 8,
      padding: 12,
      borderWidth: 1,
      borderColor: themeColors.border,
    },
    objectCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    objectCardTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: themeColors.text,
    },
    footer: {
      paddingHorizontal: 20,
      paddingBottom: 8,
      backgroundColor: themeColors.background,
      borderTopWidth: 1,
      borderTopColor: themeColors.border,
    },
    submitContainer: {
      flexDirection: 'row',
      gap: 12,
    },
    submitButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
      paddingVertical: 7,
      borderRadius: 8,
    },
    submitExitButton: {
      backgroundColor: themeColors.info,
    },
    submitSaveButton: {
      backgroundColor: themeColors.success,
    },
    submitButtonText: {
      fontSize: 14,
      fontWeight: '500',
      color: themeColors.onAccent,
    },
    submittedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 7,
      borderRadius: 8,
      backgroundColor: themeColors.success,
    },
    submittedText: {
      fontSize: 14,
      fontWeight: '500',
      color: themeColors.onAccent,
    },
    aiButtonWrapper: {
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    aiTranscribeButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: themeColors.accentPurple,
      borderRadius: 8,
    },
    aiTranscribeButtonDisabled: {
      opacity: 0.6,
    },
    aiTranscribeButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: themeColors.onAccent,
    },
    transcriptionCard: {
      margin: 16,
      backgroundColor: themeColors.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: themeColors.border,
    },
    transcriptionInput: {
      minHeight: 120,
      paddingHorizontal: 16,
      paddingVertical: 12,
      fontSize: 14,
      color: themeColors.text,
      backgroundColor: 'transparent',
      borderWidth: 0,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
    },
    audioSection: {
      backgroundColor: themeColors.surfaceElevated,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: themeColors.border,
    },
    audioHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: themeColors.surface,
      borderBottomWidth: 1,
      borderBottomColor: themeColors.border,
    },
    sectionLabel: {
      fontSize: 16,
      fontWeight: '600',
      color: themeColors.text,
    },
    audioPlayerWrapper: {
      padding: 16,
    },
    noAudioText: {
      fontSize: 14,
      color: themeColors.textMuted,
      fontStyle: 'italic',
      textAlign: 'center',
      padding: 20,
    },
    transcriptionSection: {
      backgroundColor: themeColors.surfaceElevated,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: themeColors.border,
    },
    transcriptionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: themeColors.surface,
      borderBottomWidth: 1,
      borderBottomColor: themeColors.border,
    },
  });
}
