import { StyleSheet } from 'react-native';
import type { AppColors } from './palettes';

export function createTaskDetailStyles(themeColors: AppColors) {
  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: themeColors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  taskInfoBar: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingRight: 168,
    backgroundColor: themeColors.surface,
    borderBottomWidth: 1,
    borderBottomColor: themeColors.border,
  },
  taskInfoType: {
    fontSize: 16,
    fontWeight: '600',
    color: themeColors.text,
  },
  taskInfoPriceBadge: {
    backgroundColor: themeColors.accentPurple,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  taskInfoPriceText: {
    fontSize: 14,
    fontWeight: '600',
    color: themeColors.onAccent,
  },
  annotationLayout: {
    flex: 1,
    flexDirection: 'row',
  },
  leftToolbarCol: {
    width: 80,
    backgroundColor: themeColors.surface,
    borderRightWidth: 1,
    borderRightColor: themeColors.border,
    paddingVertical: 8,
    alignItems: 'center',
    gap: 8,
  },
  toolBtnLarge: {
    width: 64,
    height: 64,
    borderRadius: 8,
    backgroundColor: themeColors.surfaceElevated,
    borderWidth: 1.5,
    borderColor: themeColors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolBtnActivePurple: {
    backgroundColor: themeColors.accent,
    borderColor: themeColors.accent,
    borderWidth: 2,
  },
  toolBtnLargeText: {
    fontSize: 10,
    fontWeight: '700',
    color: themeColors.text,
    marginTop: 4,
  },
  deleteToolBtn: {
    backgroundColor: themeColors.error,
    borderColor: themeColors.error,
  },
  deleteToolBtnText: {
    color: themeColors.onAccent,
  },
  annotationMain: {
    flex: 1,
    backgroundColor: themeColors.canvasMuted,
  },
  mediaContainer: {
    flex: 1,
    backgroundColor: themeColors.canvasMuted,
    minHeight: 400,
  },
  annotationCanvas: {
    flex: 1,
    backgroundColor: themeColors.canvasMuted,
  },
  rightPanel: {
    width: 300,
    backgroundColor: themeColors.surface,
    borderLeftWidth: 1,
    borderLeftColor: themeColors.border,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: themeColors.surfaceElevated,
    borderBottomWidth: 1,
    borderBottomColor: themeColors.border,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: themeColors.text,
  },
  sectionActions: {
    flexDirection: 'row',
    gap: 8,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: themeColors.accent,
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '500',
    color: themeColors.onAccent,
  },
  annotationList: {
    flex: 1,
    backgroundColor: themeColors.background,
  },
  annotationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: themeColors.border,
  },
  annotationItemSelected: {
    backgroundColor: themeColors.accentMuted,
  },
  annotationItemLabel: {
    flex: 1,
    fontSize: 14,
    color: themeColors.text,
  },
  annotationItemDelete: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: themeColors.error,
  },
  audioSection: {
    backgroundColor: themeColors.surfaceElevated,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: themeColors.border,
  },
  audioHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: themeColors.surface,
    borderBottomWidth: 1,
    borderBottomColor: themeColors.border,
  },
  sectionLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: themeColors.text,
  },
  audioPlayerWrapper: {
    padding: 16,
  },
  noAudioText: {
    fontSize: 14,
    color: themeColors.textMuted,
    fontStyle: 'italic',
    textAlign: 'center',
    padding: 20,
  },
  transcriptionSection: {
    backgroundColor: themeColors.surfaceElevated,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: themeColors.border,
  },
  transcriptionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: themeColors.surface,
    borderBottomWidth: 1,
    borderBottomColor: themeColors.border,
  },
  aiButtonWrapper: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  aiTranscribeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: themeColors.accent,
    borderRadius: 6,
  },
  aiTranscribeButtonDisabled: {
    opacity: 0.6,
  },
  aiTranscribeButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: themeColors.onAccent,
  },
  transcriptionCard: {
    margin: 16,
    backgroundColor: themeColors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: themeColors.border,
  },
  transcriptionInput: {
    minHeight: 120,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    color: themeColors.text,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  bottomButtonBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 6,
    backgroundColor: themeColors.surface,
    borderTopWidth: 1,
    borderTopColor: themeColors.border,
  },
  bottomLeftActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  exitButton: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: themeColors.error,
  },
  exitButtonText: {
    fontSize: 14,
    color: themeColors.error,
    fontWeight: '500',
  },
  submitExitButton: {
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: themeColors.accent,
  },
  submitExitButtonText: {
    fontSize: 14,
    color: themeColors.onAccent,
    fontWeight: '500',
  },
  submitButtonGreen: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 6,
    backgroundColor: themeColors.success,
  },
  submitButtonGreenText: {
    fontSize: 14,
    color: themeColors.onAccent,
    fontWeight: '500',
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  loadingText: {
    fontSize: 16,
    color: themeColors.textMuted,
    textAlign: 'center',
    marginTop: 20,
  },
  submittedBadgeCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: themeColors.success,
    borderRadius: 12,
  },
  submittedText: {
    fontSize: 12,
    fontWeight: '500',
    color: themeColors.onAccent,
  },
});
}
