import { StyleSheet } from 'react-native';

export const taskDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0f172a',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  taskInfoBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#1e293b',
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  taskInfoType: {
    fontSize: 16,
    fontWeight: '600',
    color: '#f1f5f9',
  },
  taskInfoPriceBadge: {
    backgroundColor: '#8b5cf6',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  taskInfoPriceText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  annotationLayout: {
    flex: 1,
    flexDirection: 'row',
  },
  leftToolbarCol: {
    width: 80,
    backgroundColor: '#1e293b',
    borderRightWidth: 1,
    borderRightColor: '#334155',
    paddingVertical: 8,
    alignItems: 'center',
    gap: 8,
  },
  toolBtnLarge: {
    width: 64,
    height: 64,
    borderRadius: 8,
    backgroundColor: '#334155',
    borderWidth: 1,
    borderColor: '#475569',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolBtnActivePurple: {
    backgroundColor: '#8b5cf6',
    borderColor: '#8b5cf6',
  },
  toolBtnLargeText: {
    fontSize: 10,
    fontWeight: '500',
    color: '#f1f5f9',
    marginTop: 4,
  },
  deleteToolBtn: {
    backgroundColor: '#dc2626',
    borderColor: '#dc2626',
  },
  deleteToolBtnText: {
    color: '#fff',
  },
  annotationMain: {
    flex: 1,
    backgroundColor: '#0f172a',
  },
  mediaContainer: {
    flex: 1,
    backgroundColor: '#0f172a',
    minHeight: 400,
  },
  annotationCanvas: {
    flex: 1,
    backgroundColor: '#0f172a',
  },
  rightPanel: {
    width: 300,
    backgroundColor: '#1e293b',
    borderLeftWidth: 1,
    borderLeftColor: '#334155',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#0f172a',
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#f1f5f9',
  },
  sectionActions: {
    flexDirection: 'row',
    gap: 8,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: '#8b5cf6',
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#fff',
  },
  annotationList: {
    flex: 1,
    backgroundColor: '#0f172a',
  },
  annotationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  annotationItemSelected: {
    backgroundColor: '#1e293b',
  },
  annotationItemLabel: {
    flex: 1,
    fontSize: 14,
    color: '#f1f5f9',
  },
  annotationItemDelete: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: '#dc2626',
  },
  audioSection: {
    backgroundColor: '#1e293b',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#334155',
  },
  audioHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#0f172a',
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  sectionLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#f1f5f9',
  },
  audioPlayerWrapper: {
    padding: 16,
  },
  noAudioText: {
    fontSize: 14,
    color: '#64748b',
    fontStyle: 'italic',
    textAlign: 'center',
    padding: 20,
  },
  transcriptionSection: {
    backgroundColor: '#1e293b',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#334155',
  },
  transcriptionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#0f172a',
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  aiButtonWrapper: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  aiTranscribeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#8b5cf6',
    borderRadius: 6,
  },
  aiTranscribeButtonDisabled: {
    opacity: 0.6,
  },
  aiTranscribeButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  transcriptionCard: {
    margin: 16,
    backgroundColor: '#0f172a',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#334155',
  },
  transcriptionInput: {
    minHeight: 120,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    color: '#f1f5f9',
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  bottomButtonBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#0f172a',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
  },
  bottomLeftActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  exitButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#ef4444',
  },
  exitButtonText: {
    fontSize: 14,
    color: '#ef4444',
    fontWeight: '600',
  },
  submitExitButton: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#3b82f6',
  },
  submitExitButtonText: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
  },
  submitButtonGreen: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: '#8b5cf6',
  },
  submitButtonGreenText: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  loadingText: {
    fontSize: 16,
    color: '#f1f5f9',
    textAlign: 'center',
    marginTop: 20,
  },
  submittedBadgeCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#22c55e',
    borderRadius: 12,
  },
  submittedText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#fff',
  },
});
