import { StyleSheet } from 'react-native';

/** Görüntü görevi (`dashboard/image/[id]`) ile aynı slate paleti */
export const proColors = {
  bg: '#0f172a',
  panel: '#1e293b',
  border: '#334155',
  accent: '#3b82f6',
  accentMuted: 'rgba(59, 130, 246, 0.15)',
  text: '#f1f5f9',
  textMuted: '#94a3b8',
  textSoft: '#64748b',
  danger: '#ef4444',
  radius: 8,
};

export const videoProWorkbenchStyles = StyleSheet.create({
  root: {
    flex: 1,
    width: '100%',
    height: '100%',
    minHeight: 480,
    backgroundColor: proColors.bg,
  },
  backHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#0f172a',
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
  },
  backButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3b82f6',
    marginLeft: 8,
  },
  mainRow: {
    flex: 1,
    flexDirection: 'row',
    minHeight: 0,
    minWidth: 0,
  },
  /** Video pro: dar şerit, az boşluk */
  leftToolRail: {
    width: 56,
    minWidth: 56,
    maxWidth: 56,
    backgroundColor: proColors.bg,
    borderRightWidth: 1,
    borderRightColor: proColors.border,
  },
  leftToolRailContent: {
    paddingVertical: 6,
    paddingHorizontal: 4,
    alignItems: 'center',
    gap: 4,
    paddingBottom: 12,
  },
  toolRailBtn: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: proColors.panel,
    borderWidth: 1,
    borderColor: proColors.border,
  },
  toolRailBtnActive: {
    borderColor: proColors.accent,
    backgroundColor: proColors.accentMuted,
  },
  rightDivider: {
    height: 1,
    backgroundColor: proColors.border,
    marginVertical: 14,
    marginHorizontal: 4,
  },
  center: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    flexDirection: 'column',
    backgroundColor: proColors.bg,
  },
  centerStack: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    flexDirection: 'row',
  },
  rightPanel: {
    flex: 0,
    width: 280,
    minWidth: 280,
    maxWidth: 280,
    backgroundColor: proColors.panel,
    borderLeftWidth: 1,
    borderLeftColor: proColors.border,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
    flexDirection: 'column',
    minHeight: 0,
  },
  rightPanelScroll: {
    paddingHorizontal: 8,
    paddingBottom: 20,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: proColors.text,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
  },
  sectionTitleRight: {
    paddingTop: 8,
    paddingHorizontal: 8,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: proColors.border,
  },
  labelRowActive: {
    backgroundColor: proColors.accentMuted,
    borderLeftWidth: 3,
    borderLeftColor: proColors.accent,
  },
  labelDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  labelText: {
    flex: 1,
    fontSize: 13,
    color: proColors.text,
  },
  labelShortcut: {
    fontSize: 11,
    color: proColors.textMuted,
  },
  /** Video: orta satırda sağ yarı (tuval solda) */
  videoWrap: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    position: 'relative',
    overflow: 'hidden' as const,
  },
  /** Kare görüntüsü: araç şeridine yakın sol yarı */
  canvasWrap: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    backgroundColor: proColors.bg,
    position: 'relative' as const,
    borderRightWidth: 1,
    borderRightColor: proColors.border,
  },
  canvasFitBar: {
    position: 'absolute',
    top: 6,
    left: 6,
    right: 6,
    zIndex: 20,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    pointerEvents: 'box-none' as const,
  },
  canvasFitButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: 'rgba(30, 41, 59, 0.94)',
    borderWidth: 1,
    borderColor: '#475569',
  },
  canvasWorkspace: {
    flex: 1,
    backgroundColor: proColors.bg,
    borderRadius: proColors.radius,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: proColors.border,
  },
  propLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: proColors.textMuted,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  propHint: {
    fontSize: 12,
    color: proColors.textSoft,
    lineHeight: 18,
    marginTop: 24,
    fontStyle: 'italic',
  },
  propHintRight: {
    fontSize: 12,
    color: proColors.textSoft,
    lineHeight: 18,
    marginTop: 8,
    marginBottom: 8,
    paddingHorizontal: 10,
    fontStyle: 'italic',
  },
  selectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: proColors.radius,
    borderWidth: 1,
    borderColor: proColors.border,
    backgroundColor: '#0f172a',
    marginBottom: 6,
  },
  selectRowText: {
    fontSize: 13,
    color: proColors.text,
    flex: 1,
  },
  deleteBtn: {
    marginTop: 16,
    paddingVertical: 10,
    borderRadius: proColors.radius,
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.45)',
    alignItems: 'center',
  },
  deleteBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: proColors.danger,
  },
  checkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 14,
    gap: 10,
  },
  checkLabel: {
    fontSize: 13,
    color: proColors.text,
  },
  readOnlyBox: {
    marginTop: 14,
    padding: 10,
    borderRadius: proColors.radius,
    borderWidth: 1,
    borderColor: proColors.border,
    backgroundColor: proColors.bg,
  },
  readOnlyLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: proColors.textMuted,
    marginBottom: 4,
  },
  readOnlyValue: {
    fontSize: 12,
    color: proColors.text,
    fontFamily: 'monospace',
  },
  loadingText: {
    color: proColors.textMuted,
    fontSize: 14,
    textAlign: 'center',
    marginTop: 40,
  },

  /** Görüntü görevi [id] ile aynı alt aksiyon çubuğu */
  bottomButtonBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#0f172a',
    borderTopWidth: 1,
    borderTopColor: '#334155',
  },
  bottomLeftActions: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  bottomRightActions: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  exitButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#ef4444',
  },
  exitButtonText: {
    fontSize: 14,
    color: '#ef4444',
    fontWeight: '600',
  },
  submitExitButton: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#3b82f6',
  },
  submitExitButtonText: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
  },
  submitButtonGreen: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#22c55e',
  },
  submitButtonGreenText: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
});
