import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const videoWorkbenchStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  mainContent: {
    flex: 1,
    flexDirection: 'row',
  },
  videoSection: {
    flex: 1,
    flexDirection: 'column',
  },
  videoContainer: {
    flex: 1,
    backgroundColor: '#000',
    position: 'relative',
  },
  video: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000',
  },
  videoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: 'none',
  },
  sidePanel: {
    width: 320,
    backgroundColor: colors.surface,
    borderLeftWidth: 1,
    borderLeftColor: colors.border,
  },
  sidePanelContent: {
    flex: 1,
  },
  // Video controls
  controlsContainer: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  videoTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 12,
  },
  playbackControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  playButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  speedControl: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  speedButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: colors.accentMuted,
    borderWidth: 1,
    borderColor: colors.accent,
  },
  speedButtonText: {
    fontSize: 12,
    color: colors.accent,
    fontWeight: '500',
  },
  timeDisplay: {
    fontSize: 14,
    color: colors.textMuted,
    fontFamily: 'monospace',
  },
  // Transcription section (video workbench: tek blok; flex:1 kartları şişirirdi)
  transcriptionSection: {
    paddingVertical: 8,
    paddingHorizontal: 0,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 12,
  },
  transcriptionContainer: {
    backgroundColor: colors.surfaceElevated,
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  transcriptionInput: {
    fontSize: 13,
    color: colors.text,
    textAlignVertical: 'top',
    minHeight: 72,
    maxHeight: 120,
    padding: 8,
  },
  transcriptionActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  actionButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: colors.accent,
  },
  actionButtonText: {
    fontSize: 12,
    color: colors.onAccent,
    fontWeight: '500',
  },
  // Annotation section
  annotationSection: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  annotationTools: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  toolButton: {
    width: 36,
    height: 36,
    borderRadius: 6,
    backgroundColor: colors.accentMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolButtonActive: {
    backgroundColor: colors.accent,
  },
  annotationCanvas: {
    flex: 1,
    backgroundColor: colors.canvasMuted,
    borderRadius: 8,
    overflow: 'hidden',
  },
  // Labels section
  labelsSection: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  labelsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  labelOption: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: 'transparent',
    borderWidth: 1,
  },
  labelOptionSelected: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  labelOptionText: {
    fontSize: 10,
    fontWeight: '500',
  },
  timeRangeInfo: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  timeRangeLabel: {
    fontSize: 11,
    color: colors.textMuted,
    marginBottom: 2,
  },

  // Bottom buttons
  bottomButtonBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 6,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  bottomLeftActions: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  bottomRightActions: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  exitButton: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors.error,
  },
  exitButtonText: {
    fontSize: 14,
    color: colors.error,
    fontWeight: '500',
  },
  submitExitButton: {
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: colors.accent,
  },
  submitExitButtonText: {
    fontSize: 14,
    color: colors.onAccent,
    fontWeight: '500',
  },
  submitButtonGreen: {
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: colors.success,
  },
  submitButtonGreenText: {
    fontSize: 14,
    color: colors.onAccent,
    fontWeight: '500',
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submittedBadgeCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: colors.success,
  },
  submittedText: {
    fontSize: 14,
    color: colors.onAccent,
    fontWeight: '600',
  },

  taskInfoBar: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingRight: 168,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexWrap: 'wrap',
    gap: 12,
  },
  taskInfoType: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  taskInfoPriceBadge: {
    backgroundColor: colors.accentPurple,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  taskInfoPriceText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.onAccent,
  },

  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    flexWrap: 'wrap',
    gap: 8,
  },
  sectionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  aiButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.accentMuted,
    borderWidth: 1,
    borderColor: colors.accent,
  },
  transcriptionScroll: {
    maxHeight: 100,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonDisabledText: {
    color: colors.textMuted,
  },
  transcriptionEditorSidebar: {
    flexGrow: 0,
    flexShrink: 0,
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },

  /** video-annotation + VideoSidebar layout (önceden eksikti; sayfa çöküyordu) */
  loadingText: {
    color: colors.textMuted,
    fontSize: 14,
    textAlign: 'center',
    marginTop: 24,
  },
  containerFullWidth: {
    width: '100%',
    maxWidth: '100%',
    alignSelf: 'stretch',
    marginHorizontal: 0,
    paddingHorizontal: 0,
  },
  annotationLayout: {
    flex: 1,
    flexDirection: 'row',
    minHeight: 0,
  },
  leftToolbarCol: {
    width: 60,
    minWidth: 60,
    maxWidth: 60,
    padding: 4,
    backgroundColor: colors.surface,
    borderRightWidth: 1,
    borderRightColor: colors.border,
    flexDirection: 'column',
    gap: 4,
  },
  toolBtnLarge: {
    width: 48,
    height: 48,
    borderRadius: 6,
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1.5,
    borderColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 1,
  },
  toolBtnActivePurple: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
    borderWidth: 2,
  },
  toolBtnLargeText: {
    fontSize: 9,
    color: colors.text,
    marginTop: 1,
    fontWeight: '700',
  },
  deleteToolBtn: {
    backgroundColor: 'rgba(220, 38, 38, 0.1)',
    borderColor: colors.error,
  },
  deleteToolBtnText: {
    color: colors.error,
  },
  annotationMain: {
    flex: 1,
    minWidth: 0,
    minHeight: 300,
    flexDirection: 'column',
  },
  videoStage: {
    width: '100%',
    flexShrink: 0,
    minHeight: 280,
    backgroundColor: '#000',
  },
  videoMissingBox: {
    flex: 1,
    minHeight: 280,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    gap: 8,
  },
  videoMissingTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textSecondary,
    textAlign: 'center',
  },
  videoMissingHint: {
    fontSize: 12,
    color: colors.textMuted,
    textAlign: 'center',
    lineHeight: 18,
    maxWidth: 420,
  },
  optionalNotesBlock: {
    marginTop: 8,
    flexShrink: 0,
  },
  optionalNotesToggle: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  optionalNotesToggleText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
  },
  annotationCanvasWrapFullWidth: {
    flex: 1,
    width: '100%',
    minHeight: 400,
    alignSelf: 'stretch',
  },
  canvasWorkspace: {
    flex: 1,
    backgroundColor: colors.canvasMuted,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
  },
  videoPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
    minHeight: 200,
  },
  videoPlaceholderText: {
    color: colors.textMuted,
    fontSize: 16,
    marginTop: 8,
  },
  rightSidebar: {
    width: 280,
    minWidth: 280,
    maxWidth: 280,
    padding: 8,
    backgroundColor: colors.surface,
    borderLeftWidth: 1,
    borderLeftColor: colors.border,
    flexDirection: 'column',
    minHeight: 0,
    alignSelf: 'stretch',
  },
  rightSidebarTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 12,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  objectList: {
    flex: 1,
    minHeight: 60,
  },
  objectListEmpty: {
    fontSize: 12,
    color: colors.textMuted,
    fontStyle: 'italic',
  },
  objectCardWrap: {
    marginBottom: 8,
  },
  objectCard: {
    backgroundColor: colors.surfaceElevated,
    borderRadius: 12,
    padding: 12,
    marginBottom: 0,
    borderWidth: 1,
    borderColor: colors.border,
  },
  objectCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  objectCardTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    flex: 1,
  },
  labelOptionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  labelOptionChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 16,
    backgroundColor: 'transparent',
    borderWidth: 1,
  },
});
